Fix: Use new api to fetch documents and thumbnails (#82)
bauerj/paperless_app pull request #87
Opened 2022-05-16 16:21 UTC by dorianim

This PR fixes #82 :)

2022-05-16 19:32 UTC, bauerj requested changes
Hey,

thanks a lot for woking on this! As you can see in more detail in the comment, this needs some slight changes to avoid incompatibility with old versions of Paperless.

It would be great if you can change your PR accordingly!

2022-05-16 19:32 UTC, bauerj commented on lib/api.dart
> +    return "${API.instance!.baseURL}/api/documents/$id/thumb/";
For users that still use the old pre-ng Paperless ("OG Paperless") this will not work. Could you check `API.instance.apiFlavour` and return the best value for either `paperless` or `paperless-ng`?

2022-05-16 19:32 UTC, bauerj commented on lib/api.dart
> +    return "${API.instance!.baseURL}/api/documents/$id/download/";
And here as well.

2022-05-16 19:49 UTC, dorianim commented on lib/api.dart
> +    return "${API.instance!.baseURL}/api/documents/$id/thumb/";
Done :)

2022-05-17 10:18 UTC, bauerj approved these changes

2022-05-17 13:47 UTC, bauerj commented
Thank you 😊

2022-05-17 13:47 UTC, merged